services:
  prometheus:
    image: prom/prometheus
    container_name: mini-lab-prometheus
    ports:
      - "19090:9090"
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - ./prometheus/alert.rules.yml:/etc/prometheus/alert.rules.yml:ro
      - prometheus-data:/prometheus
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: unless-stopped

  node-exporter:
    image: quay.io/prometheus/node-exporter:latest
    container_name: mini-lab-node-exporter
    command:
      - '--path.rootfs=/host'
    network_mode: host
    pid: host
    restart: unless-stopped
    volumes:
      - '/:/host:ro,rslave'

  alertmanager:
    image: prom/alertmanager
    container_name: mini-lab-alertmanager
    ports:
      - "19093:9093"
    volumes:
      - ./alertmanager/alertmanager.yml:/etc/alertmanager/alertmanager.yml:ro
    restart: unless-stopped

  grafana:
    image: grafana/grafana
    container_name: mini-lab-grafana
    ports:
      - "13000:3000"
    restart: unless-stopped
    volumes:
      - grafana-storage:/var/lib/grafana

volumes:
  prometheus-data: {}
  grafana-storage: {}
