apiVersion: apps/v1
kind: Deployment
metadata:
  name: mini-service-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mini-service-app
  template:
    metadata:
      labels:
        app: mini-service-app
    spec:
      containers:
        - name: app
          image: mini-service-infra-labs-app:v1
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8000
          env:
            - name: LAB_ENV
              valueFrom:
                configMapKeyRef:
                  name: mini-service-app-config
                  key: LAB_ENV
            - name: APP_SECRET_TOKEN
              valueFrom:
                secretKeyRef:
                  name: mini-service-app-secret
                  key: APP_SECRET_TOKEN
          readinessProbe:
            httpGet:
              path: /ready
              port: 8000
            initialDelaySeconds: 3
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 5
            periodSeconds: 10
